from enum import Enum

class MessageType(Enum):
    AA = "AA"
    TX = "TX"
    ON = "ON"
    DK = "DK"
    CC = "CC"
    CX = "CX"
    LS = "LS"
    HA = "HA"
    DEFAULT = "DEFAULT"

class MessageField(Enum):
    START_MESSAGE_INDICATOR = "Start Message Indicator"
    MESSAGE_TYPE = "Message Type"
    SEQUENCE_NUMBER = "Sequence Number"
    EPN_VERSION_CONTROL = "EPN Version Control"
    SUBSCRIBER_ID = "Subscriber ID"
    CONNECTION_ID = "Connection ID"
    INTERNAL_ID = "Internal ID"
    MESSAGE_ID = "Message ID"
    ACKNOWLEDGMENT_CODE = "Acknowledgment Code"
    EPN_ACK_TIMESTAMP = "EPN Ack Timestamp"
    ORIGINAL_SEQUENCE = "Original Sequence"
    FIELD_7 = "Field 7"
    FIELD_8 = "Field 8"
    NUMBER_OF_POOLS = "Number of Pools"
    FIELD_10 = "Field 10"
    END_MESSAGE_INDICATOR = "End Message Indicator"
    POOL_FIELD_1 = "Pool Field 1"
    POOL_FIELD_2 = "Pool Field 2"
